# Generated by Django 5.0.2 on 2024-03-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='categoryid')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=200)),
                ('craftmaker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('selectpayment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False, verbose_name='roleid')),
                ('rolename', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('pprize', models.IntegerField()),
                ('pdescription', models.CharField(max_length=100)),
                ('prating', models.IntegerField()),
                ('pthumbnail', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='productimages/')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.category')),
            ],
        ),
    ]
