# Generated by Django 5.0.2 on 2024-03-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='categoryid')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False, verbose_name='roleid')),
                ('rolename', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('productname', models.CharField(max_length=100)),
                ('productprize', models.IntegerField()),
                ('productdescription', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('productthumbnail', models.CharField(max_length=100)),
                ('productimage', models.ImageField(upload_to='images/')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.category')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('craftmaker', models.BooleanField(default=False)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.roles')),
            ],
        ),
    ]
