# Generated by Django 5.0.2 on 2024-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_login_roleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
