# Generated by Django 5.0.2 on 2024-03-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='address',
        ),
    ]
