# Generated by Django 5.0.2 on 2024-03-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_myimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myimage',
        ),
    ]
