# Generated by Django 5.0.2 on 2024-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_delete_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(upload_to='files/covers '),
        ),
    ]
