# Generated by Django 5.0.2 on 2024-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryid',
        ),
        migrations.AlterField(
            model_name='product',
            name='productimage',
            field=models.ImageField(upload_to='productimages/'),
        ),
    ]
