# Generated by Django 5.0.2 on 2024-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
